### ISSUE TITLE
Embedded videos not showing

### ISSUE THREAD

**Issue by xur86x** [YePpHa/YouTubeCenter#1503]
Whenever I use Youtube Center embedded videos are just a black frame. I already tested if other extensions are causing it, but it's clearly Youtube Center.

Developer build 489 on Opera

**Comment by Erroneuz** [comment]
I can confirm the same problem with v2.1.7 in Firefox 36.

**Comment by TroublePanic** [comment]
Same problem, Firefox 36, YouTubeCenter 2.1.7, Ubuntu 14.04. The new FF update had a few fascinating interactions ... but if it's showing up on Opera as well, this issue might need splitting.

**Comment by JBib** [comment]
Hi,
Same problem with youtube center 2.1.7 and Firefox 36.

**Comment by TroublePanic** [comment]
Also happening in Windows 8.1/FF 36/YTC 2.1.7

**Comment by YePpHa** [comment]
Can someone who has this issue test if it's also occurring with the [developer version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version)?

**Comment by amberkun** [comment]
i also had this problem 
w7 / FF36 / YTC 2.1.7
i turned off "enable embed" in external players settings

**Comment by ga5m5k** [comment]
development build is working fine. just the new update to ff and youtube is crap.

**Comment by ga5m5k** [comment]
also the ff add-on has no options also black screen as well same for the monkey vers.

**Comment by Erroneuz** [comment]
I can confirm, it works with developer version 492 in Firefox 36 on Windows 8.1

**Comment by xur86x** [comment]
I just switched to 492, but it still doesn't work with Opera.

**Comment by Jaitsu** [comment]
Confirming: broken in release build, fixed in dev build. Thanks! (Out of curiosity, what changed?)

**Comment by PureChaosX** [comment]
I can also confirm the same issues. FireFox update to v36 has broken external/embedded videos, creating a black screen, with no audio. Disabling embedded videos from YTCenter has no effect.

**Comment by caiorg** [comment]
I've noticed this issue too.

I've set up to use HTML5 player on embeds, but it isn't working at all. The embed keeps loading the Flash version of the player.

I'm using Flashblock's FF extension with the option to unblock by clicking on it. When I disable Youtube Center, the Flash logo appears and I can click to unblock, but if I leave Youtube Center enabled, it just stays on the black screen as everybody else here.

Don't if this helps to track down the bug, but I wanted to help somehow.

**Comment by Macdom** [comment]
Tried the dev release. Tried cleaning cookies, disabling AdBlock and NoScript. It still doesn't load.

**Comment by kjm16** [comment]
Still having this issue on Firefox 36.0.3 all embedded youtube videos show up blank.
![screen shot 2015-03-20 at 7 19 10 pm](https://cloud.githubusercontent.com/assets/7516336/6763359/10faac34-cf36-11e4-8325-929ec81479fb.png)

**Comment by ZimTester** [comment]
Hello and, again, welcome to the Jeppe Science YouTube-Aided Enrichment Center.

Same bug for me. **Fixable!** (for me, see below)

Windows 7 SP1
Chromium 44.0.2359.0 ("**Block third party cookies**" enabled)
YouTube Center Developer Build 497

##### Console log:
YouTubeCenter.js:26543 :arrow_forward: Domain registered www.youtube.com.
:warning: 'CanvasRenderingContext2D.**webkitImageSmoothingEnabled**' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead. :arrow_right: YouTubeCenter.js:23948
```javascript
ctx.webkitImageSmoothingEnabled = false;
```
:no_entry: Uncaught SecurityError: Failed to read the '**localStorage**' property from 'Window': Access is denied for this document. :arrow_right: YouTubeCenter.js:26020
```javascript
if ((value = localStorage.getItem(key) || null) !== null) {
```
> chrome_load @ YouTubeCenter.js:26020
> load @ YouTubeCenter.js:26412
> handleMethods @ YouTubeCenter.js:26226
> (anonymous function) @ YouTubeCenter.js:26192

YouTubeCenter.js:2022 :arrow_forward: [Embed] writeEmbed has been leaked to YouTube Center Developer Build.
YouTubeCenter.js:2022 :arrow_forward: [Property Wrapper] Wrapping the function undefined into a function wrapper.
YouTubeCenter.js:2022 :arrow_forward: [Property Wrapper] Property doesn't exists in parent, attaching trigger using `getter and setter`.
YouTubeCenter.js:2022 :arrow_forward: [Property Wrapper] Wrapping `create` function in a wrapper.
YouTubeCenter.js:2022 :arrow_forward: [Embed] YouTube has called writeEmbed.
YouTubeCenter.js:2022 :arrow_forward: [Embed] Checking if YouTube and YouTube Center Developer Build are ready...
YouTubeCenter.js:2022 :arrow_forward: [Embed] They're both not ready yet!

#### How to fix:
- Disable "**Block third party cookies**" in your browser settings
- Add an exception for third party cookies for this domain:
  - **[*.]youtube.com**
- Add to the beginning of **YouTubeCenter.js** (inside of *YouTube Center* extension):
```javascript
(function(localStorage) {
})(localStorage);
```
Use **any** option. In the last case the error still occurs, but embedded videos work with any browser settings and even without cookies exceptions.

**Comment by SuperSajuuk** [comment]
I noticed some bugs with embeds: if too many are loaded on the page, the entire tab will crash on the affected website. This means I have to disable Tampermonkey entirely to make the page load as normal, so I guess there's a limit to how many embeds can be processed.

**Comment by Zarggg** [comment]
@SuperSajuuk The crashing issue with numerous embedded players has been noted before, particularly in Issue #1103. Mostly this seems related to Tampermonkey loading a separate instance of the userscript for *each* instance of an embedded player on the page -- e.g., if a page has 15 embedded YouTube videos, Tampermonkey will load the *entire* YTC script into memory 15 times. 

One thing to try is to use YTC as an [unpacked extension](http://superuser.com/questions/247651/how-does-one-install-an-extension-for-chrome-browser-from-the-local-file-system/252990#252990). The .CRZ file is basically a ZIP archive with a different extension and the files within it may be unpacked to a folder.

**Comment by SuperSajuuk** [comment]
@Zarggg I don't plan on using it unpacked, ever. That method is generally very annoying and I can cope with the bug.
