### ISSUE TITLE
Youtube page stays white

### ISSUE THREAD

**Issue by Bluscream** [YePpHa/YouTubeCenter#2480]
Firefox 59.0.2 (64-Bit)
YouTube Center Developer Build 548
![](https://i.imgur.com/Vua0LNV.png)

**Comment by leandroprz** [comment]
It seems YouTube has made the new layout available for everyone and can't go back to the old one. The new layout is causing the white page.

**Comment by Bluscream** [comment]
So this addon is permanently broken then?

**Comment by Fallen10111** [comment]
There is a way to revert to the old layout. I had this issue some time back, I can't remember off the top of my head how I did it exactly but it's in your account settings or something for Youtube itself I believe. Disable YouTube center, find it, revert it, then re-enable.

**Comment by leandroprz** [comment]
I did that some time ago, but this time I can't find the option anywhere, that's why I think YouTube is rolling out the new version definitely.

**Comment by Fallen10111** [comment]
I want to say it was something to do with https://www.youtube.com/testtube . I could be wrong. I had it only a couple months back. But yeah, maybe they're fully rolling it out now. I hope not. I like YTC and the new layout was kinda bleh anyway.

**Comment by VinnyCordeiro** [comment]
@Bluscream You can install ['Youtube - Restore Classic'](https://greasyfork.org/pt-BR/scripts/34818-youtube-restore-classic) script as a workaround, as it will restore the old YouTube layout.

**Comment by Bluscream** [comment]
I'm happy with Iridium but it's always good to have a plan B :)

**Comment by leandroprz** [comment]
@VinnyCordeiro that script is not working for me.

**Comment by blinkenlight** [comment]
Stopped working since yesterday or so: the video just stays an empty black square no matter what I do, both used as add-on or script, even when reset to default settings, even with the Restore script mentioned above (Firefox 52.7.3 ESR 64-bit on Windows 7).

**Comment by Vadigor** [comment]
~~I've opened a [new issue](https://github.com/YePpHa/YouTubeCenter/issues/2483) as it seems that there's another, possibly more permanent issue now. Symptom is a black player window instead of the classic white YouTube which is normally the result of the UI redesign.~~

EDIT - For those seeing this later: the black screen bug was solved in #2481. Update to build 549 to restore normal operation.

**Comment by blinkenlight** [comment]
Awesome, 549 fixes it for me. Lots of thanks!

**Comment by VinnyCordeiro** [comment]
@leandroprz Strange, it works for me. Anyway it shouldn't be necessary anymore with build 549.

**Comment by penfold1992** [comment]
I am still having some troubles.
If I turn auto-buffering on, it will begin to buffer but I cannot play the video.
If I turn it off, when I select the video, it goes black and then seems to reload the video with the youtube play logo appearing as if I had not started the video... Any ideas?

EDIT: so if I enable auto play things seem to be working but when I prevent autoplay, I get the problem.
Can anyone reproduce?
